apiVersion: apps/v1
kind: Deployment
metadata:
  name: app4
spec:
  selector:
    matchLabels:
      app: app4
  template:
    metadata:
      labels:
        app: app4
    spec:
      containers:
      - name: app4
        image: raphadocker/goapp:1.0.3
        resources: {}
        ports:
        - containerPort: 8080
